name: graphql_fragment_builder
description: A flexible and type-safe GraphQL fragment builder for Dart and Flutter applications.
version: 1.0.0
homepage: https://github.com/gabrimatic/graphql_fragment_builder
repository: https://github.com/gabrimatic/graphql_fragment_builder
issue_tracker: https://github.com/gabrimatic/graphql_fragment_builder/issues

environment:
  sdk: ^3.5.1

dependencies:

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0